In [1]:
from google.colab import files

uploaded = files.upload()

Saving customer_shopping_behavior.csv to customer_shopping_behavior.csv

In [2]:
import pandas as pd

df = pd.read_csv("customer_shopping_behavior.csv")
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [4]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [5]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [6]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [7]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [8]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [9]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)': 'puchase_amount'})

In [10]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'puchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [11]:
# create a new column age_group
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [12]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [13]:
# create new column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [14]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [15]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [16]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [17]:
# Dropping promo code used column

df = df.drop('promo_code_used', axis=1)

In [18]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'puchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [19]:
!pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 18.3 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [20]:
from sqlalchemy import create_engine, text

engine = create_engine(
    "postgresql://neondb_owner:npg_rcbuf6SaM9Oe@ep-old-wave-apq2q9bd.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require"
)

table_name = "customer"

# Load dataframe
df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

# Verification
with engine.connect() as conn:
    count = conn.execute(
        text(f"SELECT COUNT(*) FROM {table_name}")
    ).scalar()

print(f"✅ Data successfully loaded into PostgreSQL!")
print(f"✅ Table Name: {table_name}")
print(f"✅ Total Rows Loaded: {count}")

✅ Data successfully loaded into PostgreSQL!
✅ Table Name: customer
✅ Total Rows Loaded: 3900

In [21]:
query = "SELECT * FROM customer LIMIT 5"

df_check = pd.read_sql(query, engine)

print(df_check)

   customer_id  age gender item_purchased  category  puchase_amount  \
0            1   55   Male         Blouse  Clothing              53
1            2   19   Male        Sweater  Clothing              64
2            3   50   Male          Jeans  Clothing              73
3            4   21   Male        Sandals  Footwear              90
4            5   45   Male         Blouse  Clothing              49

        location size      color  season  review_rating subscription_status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   shipping_type discount_applied  previous_purchases payment_method  \
0        Express              Yes                  14          Venmo
1        Express              Yes                   2           Cash
2  Free Shipping              Yes                  23    Credit Card
3   Next Day Air              Yes                  49         PayPal
4  Free Shipping              Yes                  31         PayPal

  frequency_of_purchases    age_group  purchase_frequency_days
0            Fortnightly  Middle-aged                       14
1            Fortnightly  Young Adult                       14
2                 Weekly  Middle-aged                        7
3                 Weekly  Young Adult                        7
4               Annually  Middle-aged                      365

**cutomer behavious analysys**

In [22]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://neondb_owner:npg_rcbuf6SaM9Oe@ep-old-wave-apq2q9bd.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require"
)

In [23]:
# Q1. Total revenue by male vs female customers
query = """
SELECT gender,
       SUM(puchase_amount) AS total_revenue
FROM customer
GROUP BY gender;
"""

result = pd.read_sql(query, engine)
result

   gender  total_revenue
0  Female        75191.0
1    Male       157890.0

In [24]:
# Q2. Customers who used a discount but spent more than average
query = """
SELECT *
FROM customer
WHERE discount_applied = 'Yes'
  AND puchase_amount >
      (SELECT AVG(puchase_amount)
       FROM customer);
"""

result = pd.read_sql(query, engine)
result

,customer_id,age,gender,item_purchased,category,puchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
1,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
2,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
3,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,49,Cash,Quarterly,Senior,90
4,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8,Venmo,Annually,Young Adult,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,1667,51,Male,Skirt,Clothing,64,Arkansas,M,Blue,Summer,3.1,No,Store Pickup,Yes,47,PayPal,Annually,Middle-aged,365
835,1671,22,Male,Pants,Clothing,73,Utah,L,Cyan,Fall,3.6,No,Free Shipping,Yes,20,Cash,Weekly,Young Adult,7
836,1673,18,Male,Boots,Footwear,73,South Carolina,L,Gold,Fall,3.8,No,Free Shipping,Yes,15,Venmo,Quarterly,Young Adult,90
837,1674,21,Male,Blouse,Clothing,62,Hawaii,M,Violet,Fall,3.4,No,Next Day Air,Yes,49,Venmo,Bi-Weekly,Young Adult,14
838,1676,35,Male,Pants,Clothing,90,Colorado,M,Beige,Spring,4.7,No,Next Day Air,Yes,21,Credit Card,Annually,Adult,365

In [25]:
# Q3. Top 5 products with highest average review rating
query = """
SELECT item_purchased,
       CAST(AVG(review_rating) AS NUMERIC(10,2)) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;
"""

result = pd.read_sql(query, engine)
result

  item_purchased  avg_rating
0         Gloves        3.86
1        Sandals        3.84
2          Boots        3.82
3            Hat        3.80
4        T-shirt        3.78

In [26]:
# Compare the average purchase amount between Standard and Express Shipping
query = """
SELECT shipping_type,
       ROUND(AVG(puchase_amount)::numeric, 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;
"""

result = pd.read_sql(query, engine)
print(result)

  shipping_type  avg_purchase_amount
0       Express                60.48
1      Standard                58.46

In [27]:
# Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
query = """
SELECT subscription_status,
       ROUND(AVG(puchase_amount)::numeric, 2) AS avg_spend,
       ROUND(SUM(puchase_amount)::numeric, 2) AS total_revenue,
       COUNT(*) AS total_orders
FROM customer
GROUP BY subscription_status;
"""

result = pd.read_sql(query, engine)
print(result)

  subscription_status  avg_spend  total_revenue  total_orders
0                  No      59.87       170436.0          2847
1                 Yes      59.49        62645.0          1053

In [28]:
query = """
SELECT customer_segment,
       COUNT(*) AS customer_count
FROM (
    SELECT CASE
        WHEN previous_purchases <= 10 THEN 'New'
        WHEN previous_purchases <= 30 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
    FROM customer
) AS segments
GROUP BY customer_segment
ORDER BY customer_count DESC;
"""

result = pd.read_sql(query, engine)

result

  customer_segment  customer_count
0        Returning            1567
1            Loyal            1549
2              New             784

In [31]:
# Q. Top 3 most purchased products within each category
query = """
WITH product_sales AS (
    SELECT category,
           item_purchased,
           COUNT(*) AS purchase_count,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(*) DESC
           ) AS rank_num
    FROM customer
    GROUP BY category, item_purchased
)

SELECT category,
       item_purchased,
       purchase_count
FROM product_sales
WHERE rank_num <= 3
ORDER BY category, purchase_count DESC;
"""

result = pd.read_sql(query, engine)

result

       category item_purchased  purchase_count
0   Accessories        Jewelry             171
1   Accessories     Sunglasses             161
2   Accessories           Belt             161
3      Clothing         Blouse             171
4      Clothing          Pants             171
5      Clothing          Shirt             169
6      Footwear        Sandals             160
7      Footwear          Shoes             150
8      Footwear       Sneakers             145
9     Outerwear         Jacket             163
10    Outerwear           Coat             161